#!/bin/sh

rm user.* img.*

echo 'insert-m
Hello
World
1413535
4123626126

insert-m
AAA1
should-be-first
4135325
2525255

insert-m
ZZZZ
should-be-last
4214124124
124124124

insert-m
Fred
freddie228
13513515
13513515

insert-m
Yurii
my-password
41351353515
135135135

ul-m
ul-s

insert-s
Hello
world.jpeg

insert-s
Yurii
personal1.png

insert-s
ZZZZ
sleepy.jpg

insert-s
ZZZZ
zzzz.png

insert-s
Yurii
personal2.jpg

insert-s
Yurii
personal3.jpeg

ul-m
ul-s

delete-m
ZZZZ

ul-m
ul-s

delete-s
5
Yurii

ul-m
ul-s

insert-m
ANewUser
new-password
135135
1351355

insert-s
ANewUser
new.png

ul-m
ul-s

update-m
AAA1
NEW-FIRST-PASS

update-s
1
Hello
world2.png

ul-m
ul-s

gc
ul-m
ul-s

exit' | ./lab1

